#!/bin/bash
set -eu

# set -x
set -o posix

test -n "${BASH:-}" && set -o pipefail

DEBUG=false
DEBUG_FLAG=--no-debug
FORCE=false
JOBS=1
NO_RUN_IF_EMPTY=false
NULL=
PRINT_FLAG=-print

main() {
	test $# -ge 1 || nope

	case "$1" in
		tree | dotfiles | node | debug | write | generate | find | html | help )
			command_"$@"
			;;
		* )
			nope
			;;
	esac
}

nope() {
	usage >&2
	exit 1
}

die() {
	# sed "s/^/overview: $1: /" >&2
	cat >&2
	exit 1
}

usage() {
	cat <<'EOF'
Usage:
    overview tree [-d] [-f] [-j <n>] <directory>
    overview dotfiles [-print] [-print0] [-f] <directory>
    overview node [-d] <file>
    overview write [-f] <file> <directory> [expression]
    overview generate <directory> [expression]
    overview find <directory> [expression]
    overview html
    overview help
EOF
}

command_help() {
	test $# -eq 0 || nope

	usage
}

command_tree() {
	while test $# -ne 0
	do
		case "$1" in
			-j | --jobs )
				shift
				JOBS="$1"
				shift
				;;
			-d | --debug | --no-debug )
				DEBUG_FLAG="$1"
				shift
				;;
			* )
				break
				;;
		esac
	done

	test $# -eq 1 || nope

	"$0" dotfiles -print0 "$1" |
		xargs -0 -n 1 -P "$JOBS" "$0" node -r "$DEBUG_FLAG"
}

command_dotfiles() {
	while test $# -ne 0
	do
		case "$1" in
			-print | -print0 )
				PRINT_FLAG="$1"
				shift
				;;
			* )
				break
				;;
		esac
	done

	# Use depth-first traversal so that if --jobs is 1
	# then ancestors can find overview*.hml files written by descendents
	set -- find "$1" -depth -type f -name '.overview*' "$PRINT_FLAG"
	# set -- "$0" debug "$@"
	exec "$@"
	exec find "$1" -depth -type f -name '.overview*' "$PRINT_FLAG"
}

command_node() {
	while test $# -ne 0
	do
		case "$1" in
			-d | --debug )
				DEBUG=true
				shift
				;;
			--no-debug )
				DEBUG=false
				shift
				;;
			-r | --no-run-if-empty )
				NO_RUN_IF_EMPTY=true
				shift
				;;
			* )
				break
				;;
		esac
	done

	# We typically get here from a `find | xargs -n 1 node`.
	# The `node` command requires one argument (a dotfile),
	# but if `find` returns no results,
	# then `xargs` will still call `node` one time with no arguments.
	#
	# GNU `find` has a `-r` / `--no-run-if-empty` flag to prevent this,
	# but it is not portable.  With GNU `find`, we can write
	#
	#     find | xargs -n 1 -r node
	#
	# Instead, we give `node` the `-r` / `--no-run-if-empty` flags,
	# so that we can portably write
	#
	#     find | xargs -n 1 node -r
	#
	"$NO_RUN_IF_EMPTY" && test $# -eq 0 && return

	test $# -eq 1 || nope

	# control stdin to empty file

	set -- "$1" "`basename -- "$1"`" "`dirname -- "$1"`"
	set -- "$1" write "$3/${2#.}.html" "$3"

	(
		shift
		$DEBUG && set -- debug "$@"
		exec xargs "$0" "$@"
	) < "$1"
}

command_validate() {
	find . -quit \( "$@" \) > /dev/null 2>&1
}

command_debug() {
	printf debug:
	if test $# -eq 0
	then
		echo ' No arguments'
	else
		printf ' "%s"' "$@"
		echo
	fi
}

command_write() {
	while test $# -ne 0
	do
		case "$1" in
			-f | --force )
				FORCE=true
				shift
				;;
			--no-force )
				FORCE=false
				shift
				;;
			* )
				break
				;;
		esac
	done

	test $# -ge 2 || nope

	if should_not_overwrite "$1"
	then
		echo "Unrecognized file already exists: $1" | die
	fi

	( shift; "$0" generate "$@" ) > "$1"
}

should_not_overwrite() {
	! $FORCE && test -f "$1" && ! has_magic < "$1"
}

has_magic() {
	head | grep -q "keebee3eing9iem6chiepourooSiequ8ezookaewoocoh0aophei4EeSh5auheij"
}

command_generate() {
	test $# -ge 1 || nope

	"$0" find "$@" | "$0" html
}

command_find() {
	test $# -ge 1 || nope

	cd "$1"
	shift

	test $# -eq 0 && set -- -name '*.html'

	exec find . -mindepth 2 -type f \( "$@" \)
}

command_html() {
	test $# -eq 0 || nope

	# sort -z | html -0
	sort | html
}

html() {
	# RS="\0"
	awk '
BEGIN {
	OFS = FS = "/"
	print "<!doctype html>"
	print "<!-- keebee3eing9iem6chiepourooSiequ8ezookaewoocoh0aophei4EeSh5auheij -->"
	print "<html lang=\"en\">"
	print "<head>"
	print "  <meta charset=\"utf-8\">"
	print "  <title>Overview</title>"
	print "  <style>"
	print "    body {"
	print "      font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\";"
	print "    }"
	print "    .title, .name {"
	print "      font-family: \"SFMono-Regular\", Consolas, \"Liberation Mono\", Menlo, Courier, monospace;"
	print "    }"
	print "  </style>"
	print "</head>"
	print "<body>"
	print "  <h1>Overview</h1>"
}

END {
	iteration_end()
	print ""
	print "</body>"
	print "</html>"
}

{ process() }

function process(    url, name, title) {
	url = $0
	name = $NF
	$NF = ""
	title = $0

	iteration_middle(title)
	item(url, name)
}

function iteration_middle(title) {
	if (iteration_changed(title))
		iteration_tick(title)
}

function iteration_changed(title,    eq) {
	eq = title == PREVIOUS
	PREVIOUS = title
	return !eq
}

function iteration_tick(title) {
	if (NR != 1)
		section_close()
	section_open(title)
}

function iteration_end() {
	if (NR)
		section_close()
}

function section_open(title) {
	print ""
	print "  <h3 class=\"title\">" title "</h3>"
	print "  <ol>"
}

function section_close() {
	print "  </ol>"
}

function item(url, name) {
	print "    <li><a class=\"name\" href=\"" url "\">" name "</a></li>"
}
'
}

main "$@"
